# conda env create -f conda_env.yaml
# conda env update -f conda_env.yaml --prune
name: ai_env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - pip
  - pip:
      - anthropic>=0.40,<1
      - prompt-toolkit>=3.0,<4
